version: '3.2'
services:
  fpm:
    build:
      context: .
    environment:
      COMPOSER_HOME: /var/cache/composer
    volumes:
      - './code:/var/www/html:cached'
      - './docker/data/composer:/var/cache/composer'

  nginx:
    depends_on:
      - fpm
    image: nginx:1.15.8-alpine
    ports:
      - '90:80'
    volumes:
      - './code/public:/var/www/html/public'
      - './docker/nginx.conf:/etc/nginx/nginx.conf:ro'

  mongo:
    image: mongo:3.4.16-jessie
    volumes:
      - './docker/data/mongo/db:/data/db'
